### ISSUE TITLE
Packaging problem

### ISSUE THREAD

**Issue by Yeregorix** [EliasLucky/TabChanger-Sponge-Plugin#1]
Here is a screenshot of the content of TabChanger-0.2.2.jar
![image](https://github.com/EliasLucky/TabChanger-Sponge-Plugin/assets/10995968/39fe63d6-a277-4289-b596-8b190326f992)
The jar includes a bunch of other jars from previous versions, and themselves include other jars. 
There are dozens of unnecessary jars in the final product. 
Sources and your IDE settings are also included. There is definitely something wrong. The final product could be way smaller.

**Comment by EliasLucky** [comment]
Yeah, that's weird, to be honest I am not professional at making sponge forge plugins, at least building them, I've tried to follow sponge documentation, but it sucked, and wasn't for sponge 1.7 so that's the problem.

I use eclipse IDE, and for building I use "clean install" command, what it does it just cleans (removes content) from ./target folder and puts new built generated plugin jar into ./target folder... To be honest I don't know what could be wrong, I've actually copied to pom.xml settings to build plugin from sponge forge wiki, and also tried to copying and pasting it into it from another plugin pom.xml for 1.7 sponge from github. So I don't know why it's there.... I can try to rebuilt the tabchanger removing unuseful jar files, which are... just previous old versions of the plugin containing the same content.... which could explain why it have big size of mb... but still... maybe I will try to do something with it, maybe there is a way to not include source files and IDE settings...

**Comment by EliasLucky** [comment]
I think I've found a solution, I've forgot to enabled filtering in build settings...

**Comment by EliasLucky** [comment]
Fixed, now the final plugin jar file is clean and small, thank you for reporting this issue. Now I know more about maven projects.

**Comment by EliasLucky** [comment]
Issue will be closed, after you test it and check it out.

**Comment by Yeregorix** [comment]
Looks good to me

**Comment by EliasLucky** [comment]
Thank you for answering, glad to hear that. Issue will be closed.
